# This file was generated by GoReleaser. DO NOT EDIT.
cask "bltctl" do
  name "bltctl"
  desc "macOS Bluetooth manager"
  homepage "https://github.com/lu-zhengda/bltctl"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bltctl"
  bash_completion "completions/bltctl.bash"
  zsh_completion "completions/bltctl.zsh"
  fish_completion "completions/bltctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/bltctl/releases/download/v#{version}/bltctl_#{version}_darwin_amd64.tar.gz"
      sha256 "64db8b7ee7d1dba04b0fc1e75025d1aa842001b8d1c8683ff8ceda1d6f53674e"
    end
    on_arm do
      url "https://github.com/lu-zhengda/bltctl/releases/download/v#{version}/bltctl_#{version}_darwin_arm64.tar.gz"
      sha256 "de3b08c7d90b4552b6e0c25790c867f87032a7a1c66de47a0ca06df0a1de0594"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bltctl"]
    end
  end

  # No zap stanza required
end
