# This file was generated by GoReleaser. DO NOT EDIT.
cask "bltctl" do
  name "bltctl"
  desc "macOS Bluetooth manager"
  homepage "https://github.com/lu-zhengda/bltctl"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bltctl"
  bash_completion "completions/bltctl.bash"
  zsh_completion "completions/bltctl.zsh"
  fish_completion "completions/bltctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/bltctl/releases/download/v#{version}/bltctl_#{version}_darwin_amd64.tar.gz"
      sha256 "b53281c02a3a93d4ff8f31c84fc74c0121b3e989bb22fdeeff5056ba1e892d4e"
    end
    on_arm do
      url "https://github.com/lu-zhengda/bltctl/releases/download/v#{version}/bltctl_#{version}_darwin_arm64.tar.gz"
      sha256 "7f1d2c83758624edbe472a9fa37f415ba912cb725f159901133756bb51078347"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bltctl"]
    end
  end

  # No zap stanza required
end
