# This file was generated by GoReleaser. DO NOT EDIT.
cask "bltctl" do
  name "bltctl"
  desc "macOS Bluetooth manager"
  homepage "https://github.com/lu-zhengda/bltctl"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bltctl"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/bltctl/releases/download/v#{version}/bltctl_#{version}_darwin_amd64.tar.gz"
      sha256 "f10cf60e556ea744a78ccb31d8ee6b9002fecfa688f5a073ca8ea237844aa961"
    end
    on_arm do
      url "https://github.com/lu-zhengda/bltctl/releases/download/v#{version}/bltctl_#{version}_darwin_arm64.tar.gz"
      sha256 "dcca337f73342cd8604ae8b545868c25f590b971d7ed505d6b50ab4c3d42da52"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bltctl"]
    end
  end

  # No zap stanza required
end
