# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-mem-viz" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "817ef52e9325e86dcb108e3ca5365f603c2950e9e239d4bd29de13db0deeae19"
      url "https://github.com/lu-zhengda/claude-mem-viz/releases/download/v#{version}/claude-mem-viz_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "30da1d73de8456fa68f662369c95855f2ace0646c6c8cffc07234c3777680465"
      url "https://github.com/lu-zhengda/claude-mem-viz/releases/download/v#{version}/claude-mem-viz_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "33b19c6398cd8b39603c60ffdcebae18e986a81a1ce22431853875b7960275ed"
      url "https://github.com/lu-zhengda/claude-mem-viz/releases/download/v#{version}/claude-mem-viz_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c493f7a924151250853e759f7806734c3e6e248dd496d78e21f4e4eb656f40a"
      url "https://github.com/lu-zhengda/claude-mem-viz/releases/download/v#{version}/claude-mem-viz_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-mem-viz"
  desc "TUI for browsing and editing Claude Code auto-memory files"
  homepage "https://github.com/lu-zhengda/claude-mem-viz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-mem-viz"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-mem-viz"]
    end
  end

  # No zap stanza required

end
