# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-mem-viz" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "08c0d0516b98f02ef8e854307a1539ddbba087c5e1998c89c966a7acc4ac17e5"
      url "https://github.com/lu-zhengda/claude-mem-viz/releases/download/v#{version}/claude-mem-viz_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e8329a5849ef5e7b8ca9284ec5965d642dbcdc2143b0c54881cc0e788b853c06"
      url "https://github.com/lu-zhengda/claude-mem-viz/releases/download/v#{version}/claude-mem-viz_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a477f1cd52c9b0fa97a4458dfbd8cd7d8828cfcb44b015fa0da4fdd3cc2b4a24"
      url "https://github.com/lu-zhengda/claude-mem-viz/releases/download/v#{version}/claude-mem-viz_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3b1044ae68e6a06ebd83481cbcf6b5e0580df9bd84a34827d50572d0c864dcb"
      url "https://github.com/lu-zhengda/claude-mem-viz/releases/download/v#{version}/claude-mem-viz_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-mem-viz"
  desc "TUI for browsing and editing Claude Code auto-memory files"
  homepage "https://github.com/lu-zhengda/claude-mem-viz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-mem-viz"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-mem-viz"]
    end
  end

  # No zap stanza required

end
