# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-mem-viz" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "737af93285dcd9f90a0e6278fae5530164de722fa9e2b2fccfd22f116d5e77a0"
      url "https://github.com/lu-zhengda/claude-mem-viz/releases/download/v#{version}/claude-mem-viz_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6a9401195f64910bcd5212e9fcd3641adf5e057f4ea182fd514d260251de57c9"
      url "https://github.com/lu-zhengda/claude-mem-viz/releases/download/v#{version}/claude-mem-viz_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9660ec496ca85229e84a948b2f236c462a193e9fe076c0838066700ef337a35f"
      url "https://github.com/lu-zhengda/claude-mem-viz/releases/download/v#{version}/claude-mem-viz_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a46fe065f41d152cc359a2ebd90d121536053b1d3334686f95ebedcea338fb00"
      url "https://github.com/lu-zhengda/claude-mem-viz/releases/download/v#{version}/claude-mem-viz_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-mem-viz"
  desc "TUI for browsing and editing Claude Code auto-memory files"
  homepage "https://github.com/lu-zhengda/claude-mem-viz"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-mem-viz"

  postflight_steps do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-mem-viz"]
    end
  end

  # No zap stanza required

end
