# This file was generated by GoReleaser. DO NOT EDIT.
cask "lanchr" do
  name "lanchr"
  desc "A macOS launch agent/daemon manager"
  homepage "https://github.com/lu-zhengda/lanchr"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lanchr"
  bash_completion "completions/lanchr.bash"
  zsh_completion "completions/lanchr.zsh"
  fish_completion "completions/lanchr.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/lanchr/releases/download/v#{version}/lanchr_#{version}_darwin_amd64.tar.gz"
      sha256 "6499c713b8b63fac4e26e348f869d0c835d6e7725fc6eda78241a82852cf8faf"
    end
    on_arm do
      url "https://github.com/lu-zhengda/lanchr/releases/download/v#{version}/lanchr_#{version}_darwin_arm64.tar.gz"
      sha256 "9247d4ad505c8347dbcf5ad901e83e553557e134eec1fe6132a3fe8ce97b33d2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lanchr"]
    end
  end

  # No zap stanza required
end
