# This file was generated by GoReleaser. DO NOT EDIT.
cask "lanchr" do
  name "lanchr"
  desc "A macOS launch agent/daemon manager"
  homepage "https://github.com/lu-zhengda/lanchr"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lanchr"
  bash_completion "completions/lanchr.bash"
  zsh_completion "completions/lanchr.zsh"
  fish_completion "completions/lanchr.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/lanchr/releases/download/v#{version}/lanchr_#{version}_darwin_amd64.tar.gz"
      sha256 "c0c7bedaf73db31547425620aeb2bd5b45713f0babff22f97f427944e890ad61"
    end
    on_arm do
      url "https://github.com/lu-zhengda/lanchr/releases/download/v#{version}/lanchr_#{version}_darwin_arm64.tar.gz"
      sha256 "d3f2538b3a81e1b31fbb6fc5a1d24c237b1b7a8fb84a3e1a29f5d4aa68a38034"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lanchr"]
    end
  end

  # No zap stanza required
end
