# This file was generated by GoReleaser. DO NOT EDIT.
cask "lanchr" do
  name "lanchr"
  desc "A macOS launch agent/daemon manager"
  homepage "https://github.com/lu-zhengda/lanchr"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lanchr"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/lanchr/releases/download/v#{version}/lanchr_#{version}_darwin_amd64.tar.gz"
      sha256 "a17892ae93391bd0612d5a22cfb5e909ffb034f9e7d35e6f710a897543286e54"
    end
    on_arm do
      url "https://github.com/lu-zhengda/lanchr/releases/download/v#{version}/lanchr_#{version}_darwin_arm64.tar.gz"
      sha256 "ce03c8471de53c5afff4e8ee5ceaa14eb63c0d75a11947434d2b6392c50536bf"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/lanchr"]
    end
  end

  # No zap stanza required
end
