# This file was generated by GoReleaser. DO NOT EDIT.
cask "macbroom" do
  name "macbroom"
  desc "A lightweight macOS cleanup tool"
  homepage "https://github.com/lu-zhengda/macbroom"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macbroom"
  bash_completion "completions/macbroom.bash"
  zsh_completion "completions/macbroom.zsh"
  fish_completion "completions/macbroom.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/macbroom/releases/download/v#{version}/macbroom_#{version}_darwin_amd64.tar.gz"
      sha256 "2147f50d61787f6bdf0fb3830548e3763e48d6fa6236108f416bf645ccd22e35"
    end
    on_arm do
      url "https://github.com/lu-zhengda/macbroom/releases/download/v#{version}/macbroom_#{version}_darwin_arm64.tar.gz"
      sha256 "5a3377b7d0c86bdab0699e1f91a5ed2727d89d8dff393a542b94c2599d2d7c68"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macbroom"]
    end
  end

  # No zap stanza required
end
