# This file was generated by GoReleaser. DO NOT EDIT.
cask "macbroom" do
  name "macbroom"
  desc "A lightweight macOS cleanup tool"
  homepage "https://github.com/lu-zhengda/macbroom"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macbroom"
  bash_completion "completions/macbroom.bash"
  zsh_completion "completions/macbroom.zsh"
  fish_completion "completions/macbroom.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/macbroom/releases/download/v#{version}/macbroom_#{version}_darwin_amd64.tar.gz"
      sha256 "d2b638e0785653376206967c596eb312dd9d3e546d45a34962e629415c89ecec"
    end
    on_arm do
      url "https://github.com/lu-zhengda/macbroom/releases/download/v#{version}/macbroom_#{version}_darwin_arm64.tar.gz"
      sha256 "00706338f51bdfc26d22501eb799c6c70166c4fba365466e3573787a96583df4"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macbroom"]
    end
  end

  # No zap stanza required
end
