# This file was generated by GoReleaser. DO NOT EDIT.
cask "macbroom" do
  name "macbroom"
  desc "A lightweight macOS cleanup tool"
  homepage "https://github.com/lu-zhengda/macbroom"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macbroom"
  bash_completion "completions/macbroom.bash"
  zsh_completion "completions/macbroom.zsh"
  fish_completion "completions/macbroom.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/macbroom/releases/download/v#{version}/macbroom_#{version}_darwin_amd64.tar.gz"
      sha256 "37e0c3a2d20166c0c3870dc3ebaa5e667ea832dc944e6f45e60767808c567303"
    end
    on_arm do
      url "https://github.com/lu-zhengda/macbroom/releases/download/v#{version}/macbroom_#{version}_darwin_arm64.tar.gz"
      sha256 "8ba9175169da8d8bc01688bcd1bcf8517df1f52c30a817d47cef15f63ac9cce5"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macbroom"]
    end
  end

  # No zap stanza required
end
