# This file was generated by GoReleaser. DO NOT EDIT.
cask "macctl" do
  name "macctl"
  desc "macOS environment controller"
  homepage "https://github.com/lu-zhengda/macctl"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macctl"
  bash_completion "completions/macctl.bash"
  zsh_completion "completions/macctl.zsh"
  fish_completion "completions/macctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/macctl/releases/download/v#{version}/macctl_#{version}_darwin_amd64.tar.gz"
      sha256 "e4e6fe8f199e4f18898a36f46cbf80e4cd1f13798db60be7837feb3e96a70064"
    end
    on_arm do
      url "https://github.com/lu-zhengda/macctl/releases/download/v#{version}/macctl_#{version}_darwin_arm64.tar.gz"
      sha256 "d5228234650272fb1cf87890e58bb6c9d8b75145745f763353f4e04a56ce7093"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macctl"]
    end
  end

  # No zap stanza required
end
