# This file was generated by GoReleaser. DO NOT EDIT.
cask "macctl" do
  name "macctl"
  desc "macOS environment controller"
  homepage "https://github.com/lu-zhengda/macctl"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macctl"
  bash_completion "completions/macctl.bash"
  zsh_completion "completions/macctl.zsh"
  fish_completion "completions/macctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/macctl/releases/download/v#{version}/macctl_#{version}_darwin_amd64.tar.gz"
      sha256 "307c4ce8b2fe943a0d8fe5567010cd97c534a950305faea578e2fcf09b4c4ad9"
    end
    on_arm do
      url "https://github.com/lu-zhengda/macctl/releases/download/v#{version}/macctl_#{version}_darwin_arm64.tar.gz"
      sha256 "84a68f1a628ee07b41bc78bb90872ee547a9669ff4faf1286087a4af3bbfde4d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macctl"]
    end
  end

  # No zap stanza required
end
