# This file was generated by GoReleaser. DO NOT EDIT.
cask "macctl" do
  name "macctl"
  desc "macOS environment controller"
  homepage "https://github.com/lu-zhengda/macctl"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macctl"
  bash_completion "completions/macctl.bash"
  zsh_completion "completions/macctl.zsh"
  fish_completion "completions/macctl.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/macctl/releases/download/v#{version}/macctl_#{version}_darwin_amd64.tar.gz"
      sha256 "5d4a81a87f6a73cc2c99f1fd7be4994929968d28e3e4c2a253f896e3d226afb3"
    end
    on_arm do
      url "https://github.com/lu-zhengda/macctl/releases/download/v#{version}/macctl_#{version}_darwin_arm64.tar.gz"
      sha256 "a476ef0cd68b47f60e62753418a69aef753d5a9999933681c9f148c338a592fd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macctl"]
    end
  end

  # No zap stanza required
end
