# This file was generated by GoReleaser. DO NOT EDIT.
cask "macdog" do
  name "macdog"
  desc "macOS security and privacy suite"
  homepage "https://github.com/lu-zhengda/macdog"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macdog"
  bash_completion "completions/macdog.bash"
  zsh_completion "completions/macdog.zsh"
  fish_completion "completions/macdog.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/macdog/releases/download/v#{version}/macdog_#{version}_darwin_amd64.tar.gz"
      sha256 "3c3647856342172644b2e3c4d4301fc7866cdcb38fe84330e7bb83f8447da425"
    end
    on_arm do
      url "https://github.com/lu-zhengda/macdog/releases/download/v#{version}/macdog_#{version}_darwin_arm64.tar.gz"
      sha256 "f0c561c1b1b589b8d66ec283f26df6b5dd4e02e0fd8ebfdc741f9c4e5c07ea6f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macdog"]
    end
  end

  # No zap stanza required
end
