# This file was generated by GoReleaser. DO NOT EDIT.
cask "macdog" do
  name "macdog"
  desc "macOS security and privacy suite"
  homepage "https://github.com/lu-zhengda/macdog"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macdog"
  bash_completion "completions/macdog.bash"
  zsh_completion "completions/macdog.zsh"
  fish_completion "completions/macdog.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/macdog/releases/download/v#{version}/macdog_#{version}_darwin_amd64.tar.gz"
      sha256 "4fce857a96b1960f21c8312b491dfbb6a1868150a4011268801d6eb0bcac4b13"
    end
    on_arm do
      url "https://github.com/lu-zhengda/macdog/releases/download/v#{version}/macdog_#{version}_darwin_arm64.tar.gz"
      sha256 "deace6b73dc2aa67a2125ec4907d8c35637cbdc12682b58b09eb37a942240b39"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macdog"]
    end
  end

  # No zap stanza required
end
