# This file was generated by GoReleaser. DO NOT EDIT.
cask "macfig" do
  name "macfig"
  desc "macOS hidden defaults manager"
  homepage "https://github.com/lu-zhengda/macfig"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macfig"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/macfig/releases/download/v#{version}/macfig_#{version}_darwin_amd64.tar.gz"
      sha256 "e70e8078a47f4255afc9455a518544537b33e3c77788e195eb02dc9596a41ab0"
    end
    on_arm do
      url "https://github.com/lu-zhengda/macfig/releases/download/v#{version}/macfig_#{version}_darwin_arm64.tar.gz"
      sha256 "f319ae2f979ee67b59962796319cd1bab652e2873ec41c37af6310cdbe34a1e1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macfig"]
    end
  end

  # No zap stanza required
end
