# This file was generated by GoReleaser. DO NOT EDIT.
cask "macfig" do
  name "macfig"
  desc "macOS hidden defaults manager"
  homepage "https://github.com/lu-zhengda/macfig"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "macfig"
  bash_completion "completions/macfig.bash"
  zsh_completion "completions/macfig.zsh"
  fish_completion "completions/macfig.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/macfig/releases/download/v#{version}/macfig_#{version}_darwin_amd64.tar.gz"
      sha256 "15f0c92fdce300fbded4631d52f2e578666c62cc52fcef3c5ced2b4e20ebb0b9"
    end
    on_arm do
      url "https://github.com/lu-zhengda/macfig/releases/download/v#{version}/macfig_#{version}_darwin_arm64.tar.gz"
      sha256 "714be2ddd39255f7d851ad607f89c0fb163738989cf418fb07a9af5c77b9e7d1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/macfig"]
    end
  end

  # No zap stanza required
end
