# This file was generated by GoReleaser. DO NOT EDIT.
cask "machealth" do
  name "machealth"
  desc "macOS system health checker for AI agents"
  homepage "https://github.com/lu-zhengda/machealth"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "machealth"
  bash_completion "completions/machealth.bash"
  zsh_completion "completions/machealth.zsh"
  fish_completion "completions/machealth.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/machealth/releases/download/v#{version}/machealth_#{version}_darwin_amd64.tar.gz"
      sha256 "45f240cd728988094f5e96ca6e38c6ce5a64ca7a4d183cada857661d77a1dad9"
    end
    on_arm do
      url "https://github.com/lu-zhengda/machealth/releases/download/v#{version}/machealth_#{version}_darwin_arm64.tar.gz"
      sha256 "5488543d6b688b3329739a3710de275442d64e467d0a9d950ca82401577a5c72"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/machealth"]
    end
  end

  # No zap stanza required
end
