# This file was generated by GoReleaser. DO NOT EDIT.
cask "netwhiz" do
  name "netwhiz"
  desc "A network diagnostics toolkit for macOS"
  homepage "https://github.com/lu-zhengda/netwhiz"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "netwhiz"
  bash_completion "completions/netwhiz.bash"
  zsh_completion "completions/netwhiz.zsh"
  fish_completion "completions/netwhiz.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/netwhiz/releases/download/v#{version}/netwhiz_#{version}_darwin_amd64.tar.gz"
      sha256 "948f17d437779b7121001c569a5ccc59773b69f57de48676c5dd089b20db6714"
    end
    on_arm do
      url "https://github.com/lu-zhengda/netwhiz/releases/download/v#{version}/netwhiz_#{version}_darwin_arm64.tar.gz"
      sha256 "fbab55d5f676d91d3f0fad0a7a4befae9cdf71c5d7b668121505725bdbd0e6a9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/netwhiz"]
    end
  end

  # No zap stanza required
end
