# This file was generated by GoReleaser. DO NOT EDIT.
cask "netwhiz" do
  name "netwhiz"
  desc "A network diagnostics toolkit for macOS"
  homepage "https://github.com/lu-zhengda/netwhiz"
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "netwhiz"
  bash_completion "completions/netwhiz.bash"
  zsh_completion "completions/netwhiz.zsh"
  fish_completion "completions/netwhiz.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/netwhiz/releases/download/v#{version}/netwhiz_#{version}_darwin_amd64.tar.gz"
      sha256 "fe83ee2f483e04c533fe852dd4d34a4ae289ba561851bb6919f81a2630802fce"
    end
    on_arm do
      url "https://github.com/lu-zhengda/netwhiz/releases/download/v#{version}/netwhiz_#{version}_darwin_arm64.tar.gz"
      sha256 "0f6e70dcdc0031e81b554b9ad3be99da3819ac9f773157f743550bfb06389cb9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/netwhiz"]
    end
  end

  # No zap stanza required
end
