# This file was generated by GoReleaser. DO NOT EDIT.
cask "pstop" do
  name "pstop"
  desc "Process explorer for macOS"
  homepage "https://github.com/lu-zhengda/pstop"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pstop"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/pstop/releases/download/v#{version}/pstop_#{version}_darwin_amd64.tar.gz"
      sha256 "7bcabe90aff4ad6adf1210cf443e8f2e4ee71049280245ed1101bf61491b27be"
    end
    on_arm do
      url "https://github.com/lu-zhengda/pstop/releases/download/v#{version}/pstop_#{version}_darwin_arm64.tar.gz"
      sha256 "e993f38b208f8cd3ff4c9d394c0f89b0b8aa4e2e73292a5598932514ce86483f"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pstop"]
    end
  end

  # No zap stanza required
end
