# This file was generated by GoReleaser. DO NOT EDIT.
cask "pstop" do
  name "pstop"
  desc "Process explorer for macOS"
  homepage "https://github.com/lu-zhengda/pstop"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pstop"
  bash_completion "completions/pstop.bash"
  zsh_completion "completions/pstop.zsh"
  fish_completion "completions/pstop.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/pstop/releases/download/v#{version}/pstop_#{version}_darwin_amd64.tar.gz"
      sha256 "bcaa1bd4d36b554775f5c7bdf84446b13a45cca158c008b73bbb94795592fd2f"
    end
    on_arm do
      url "https://github.com/lu-zhengda/pstop/releases/download/v#{version}/pstop_#{version}_darwin_arm64.tar.gz"
      sha256 "f33968dac2237f5f4e0671a4fc48335c680127952bb34a8b0ec042bc13647a3e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pstop"]
    end
  end

  # No zap stanza required
end
