# This file was generated by GoReleaser. DO NOT EDIT.
cask "pstop" do
  name "pstop"
  desc "Process explorer for macOS"
  homepage "https://github.com/lu-zhengda/pstop"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pstop"
  bash_completion "completions/pstop.bash"
  zsh_completion "completions/pstop.zsh"
  fish_completion "completions/pstop.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/pstop/releases/download/v#{version}/pstop_#{version}_darwin_amd64.tar.gz"
      sha256 "ec2731435f5a9902b7eca043df65c384c6db3ea0e3c23c097b753969dfe6fe7e"
    end
    on_arm do
      url "https://github.com/lu-zhengda/pstop/releases/download/v#{version}/pstop_#{version}_darwin_arm64.tar.gz"
      sha256 "de636c14ed628231ccbc54f23a0600c9a43db99446308c26af891d329fea0541"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pstop"]
    end
  end

  # No zap stanza required
end
