# This file was generated by GoReleaser. DO NOT EDIT.
cask "termail" do
  name "termail"
  desc "Terminal email client with Gmail support"
  homepage "https://github.com/lu-zhengda/termail"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termail"
  bash_completion "completions/termail.bash"
  zsh_completion "completions/termail.zsh"
  fish_completion "completions/termail.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/termail/releases/download/v#{version}/termail_#{version}_darwin_amd64.tar.gz"
      sha256 "6b432087ee7fb8235b69044bb45e2dd025b83e04fc6563ad3ff2a66c807a12f0"
    end
    on_arm do
      url "https://github.com/lu-zhengda/termail/releases/download/v#{version}/termail_#{version}_darwin_arm64.tar.gz"
      sha256 "64aaad76159ad8d88ef02f539a420cd831fe6fa017848682947081356fd36707"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termail"]
    end
  end

  # No zap stanza required
end
