# This file was generated by GoReleaser. DO NOT EDIT.
cask "termail" do
  name "termail"
  desc "Terminal email client with Gmail support"
  homepage "https://github.com/lu-zhengda/termail"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termail"
  bash_completion "completions/termail.bash"
  zsh_completion "completions/termail.zsh"
  fish_completion "completions/termail.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/termail/releases/download/v#{version}/termail_#{version}_darwin_amd64.tar.gz"
      sha256 "2d61652b790d441ddf3b4b297a374be53b09f5ba21aa4793892cb534b5ac5ac4"
    end
    on_arm do
      url "https://github.com/lu-zhengda/termail/releases/download/v#{version}/termail_#{version}_darwin_arm64.tar.gz"
      sha256 "0dc3f5cb1be39b1a4fa2870777720df2b67a765fe58d73e6ede0deeac9f193ee"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termail"]
    end
  end

  # No zap stanza required
end
