# This file was generated by GoReleaser. DO NOT EDIT.
cask "termail" do
  name "termail"
  desc "Terminal email client with Gmail support"
  homepage "https://github.com/lu-zhengda/termail"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termail"
  bash_completion "completions/termail.bash"
  zsh_completion "completions/termail.zsh"
  fish_completion "completions/termail.fish"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/termail/releases/download/v#{version}/termail_#{version}_darwin_amd64.tar.gz"
      sha256 "053c4f32ea2c1b323a61881ab8ec0dd44ed1213a7fc9cc31178ce54ee6650dcc"
    end
    on_arm do
      url "https://github.com/lu-zhengda/termail/releases/download/v#{version}/termail_#{version}_darwin_arm64.tar.gz"
      sha256 "9ff26a182decb971c1ae86670edf87a609e795a7b9fd038af2bd8eaefa688062"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termail"]
    end
  end

  # No zap stanza required
end
