# This file was generated by GoReleaser. DO NOT EDIT.
cask "updater" do
  app "Updater.app"

  version "0.18.4"

  on_macos do
    sha256 "de0dd4e7382665ff82dbb8329c92af830f1e0ffeea31277c72948cff696d739e"
    url "https://github.com/lu-zhengda/updater/releases/download/v#{version}/updater_#{version}_darwin.tar.gz"
  end

  name "updater"
  desc "macOS app update manager"
  homepage "https://github.com/lu-zhengda/updater"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "mas",
    ]

  binary "#{appdir}/Updater.app/Contents/MacOS/updater"
  bash_completion "completions/updater.bash"
  fish_completion "completions/updater.fish"
  zsh_completion "completions/updater.zsh"

  preflight_steps do
    if OS.mac?
      # Replace a manually-placed copy (e.g. from the release tarball);
      # Homebrew refuses to overwrite an app it did not install.
      remove "Updater.app", base: :appdir, recursive: true
    end
  end

  # No zap stanza required

end
