# This file was generated by GoReleaser. DO NOT EDIT.
cask "updater" do
  name "updater"
  desc "macOS app update manager"
  homepage "https://github.com/lu-zhengda/updater"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "updater"
  bash_completion "completions/updater.bash"
  zsh_completion "completions/updater.zsh"
  fish_completion "completions/updater.fish"

  on_macos do
    url "https://github.com/lu-zhengda/updater/releases/download/v#{version}/updater_#{version}_darwin.tar.gz"
    sha256 "259ab8e20eaf983ffecc3fd623c95756667e13aec50f93a771c1fdad6519a3ff"
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/updater"]
    end
  end

  # No zap stanza required
end
