# This file was generated by GoReleaser. DO NOT EDIT.
cask "whport" do
  name "whport"
  desc "Port & process manager for macOS"
  homepage "https://github.com/lu-zhengda/whport"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whport"

  on_macos do
    on_intel do
      url "https://github.com/lu-zhengda/whport/releases/download/v#{version}/whport_#{version}_darwin_amd64.tar.gz"
      sha256 "7e03e7bfad5510a0d0f9c284fba08fb0291a620afa30a29b66654b83a4f9a9a8"
    end
    on_arm do
      url "https://github.com/lu-zhengda/whport/releases/download/v#{version}/whport_#{version}_darwin_arm64.tar.gz"
      sha256 "e2aafcd2f70d8fb72c0188052f80eb7d6a07711db1624d4782bc503f68c8f319"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/whport"]
    end
  end

  # No zap stanza required
end
