# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lanchr < Formula
  desc "A macOS launch agent/daemon manager"
  homepage "https://github.com/zhengda-lu/lanchr"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lu-zhengda/lanchr/releases/download/v0.1.0/lanchr_0.1.0_darwin_amd64.tar.gz"
    sha256 "1e06f8ebd7f127595404ce2685f7495be15ab65e0123cc50fc5b4e80ec71f566"

    def install
      bin.install "lanchr"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lu-zhengda/lanchr/releases/download/v0.1.0/lanchr_0.1.0_darwin_arm64.tar.gz"
    sha256 "2e4434293d9306af5668b9c258e8fdbc715e9bb6be79917913a95773eee5a8ef"

    def install
      bin.install "lanchr"
    end
  end

  test do
    system "#{bin}/lanchr", "--version"
  end
end
