# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Macbroom < Formula
  desc "A lightweight macOS cleanup tool"
  homepage "https://github.com/lu-zhengda/macbroom"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lu-zhengda/macbroom/releases/download/v0.1.0/macbroom_0.1.0_darwin_amd64.tar.gz"
    sha256 "8a26adcd4ae0842d7c0f82f922eeaf369ceede2527ea3fcdca001e4174c145ca"

    def install
      bin.install "macbroom"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lu-zhengda/macbroom/releases/download/v0.1.0/macbroom_0.1.0_darwin_arm64.tar.gz"
    sha256 "9f214e3ee7cdcd6b654d2803cb5221ba0dd744d047d2a89ba36ada80b4810ed0"

    def install
      bin.install "macbroom"
    end
  end

  test do
    system "#{bin}/macbroom", "--version"
  end
end
