# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Macbroom < Formula
  desc "A lightweight macOS cleanup tool"
  homepage "https://github.com/lu-zhengda/macbroom"
  version "0.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lu-zhengda/macbroom/releases/download/v0.2.0/macbroom_0.2.0_darwin_amd64.tar.gz"
    sha256 "1f234bf1a967b3fe0628b08019146e86eb1178cdbaed85813b603f89d3a204dc"

    def install
      bin.install "macbroom"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lu-zhengda/macbroom/releases/download/v0.2.0/macbroom_0.2.0_darwin_arm64.tar.gz"
    sha256 "86e9d5db9bf8b0fc7bb83bda899b2ea99c097e834c18360f445da17aee87256e"

    def install
      bin.install "macbroom"
    end
  end

  test do
    system "#{bin}/macbroom", "--version"
  end
end
