# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Macfig < Formula
  desc "macOS hidden defaults manager"
  homepage "https://github.com/lu-zhengda/macfig"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lu-zhengda/macfig/releases/download/v0.1.0/macfig_0.1.0_darwin_amd64.tar.gz"
    sha256 "05c72b4bfe0c533e9a12066ec7f1d6f2681fdb8a45c7376598dbd62cc9106056"

    def install
      bin.install "macfig"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lu-zhengda/macfig/releases/download/v0.1.0/macfig_0.1.0_darwin_arm64.tar.gz"
    sha256 "7ceab0688623bb6ba3654a353955d9d5f409641c6554e22c13135b076728a8dd"

    def install
      bin.install "macfig"
    end
  end

  test do
    system "#{bin}/macfig", "--version"
  end
end
