# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Netwhiz < Formula
  desc "A network diagnostics toolkit for macOS"
  homepage "https://github.com/zhengda-lu/netwhiz"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lu-zhengda/netwhiz/releases/download/v0.1.0/netwhiz_0.1.0_darwin_amd64.tar.gz"
    sha256 "edf1bb92e51f7d50535823e2c298dc9acc8ea86aa546c4c008317fd1b25aa5a2"

    def install
      bin.install "netwhiz"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lu-zhengda/netwhiz/releases/download/v0.1.0/netwhiz_0.1.0_darwin_arm64.tar.gz"
    sha256 "54bc669e413eaf064201ba8d061f2a9338415311c6a11281a78f1405a1c9286a"

    def install
      bin.install "netwhiz"
    end
  end

  test do
    system "#{bin}/netwhiz", "--version"
  end
end
