# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tidymac < Formula
  desc "A lightweight macOS cleanup tool"
  homepage "https://github.com/lu-zhengda/tidymac"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lu-zhengda/tidymac/releases/download/v0.0.1/tidymac_0.0.1_darwin_amd64.tar.gz"
    sha256 "aab2e6f5e9cfbfd50de006bf33d0e9d983686e500302f9d1188a175c87541b84"

    def install
      bin.install "tidymac"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lu-zhengda/tidymac/releases/download/v0.0.1/tidymac_0.0.1_darwin_arm64.tar.gz"
    sha256 "8f87c086e7b51bba5ca3047a4085418be263f39ad12270acab13e846e03edb63"

    def install
      bin.install "tidymac"
    end
  end

  test do
    system "#{bin}/tidymac", "--version"
  end
end
