# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tidymac < Formula
  desc "A lightweight macOS cleanup tool"
  homepage "https://github.com/lu-zhengda/tidymac"
  version "0.0.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lu-zhengda/tidymac/releases/download/v0.0.3/tidymac_0.0.3_darwin_amd64.tar.gz"
    sha256 "eb2d3714c2e3b21eecc2660bf8ee4bd824a53a81cae87458a1fd870c98a60064"

    def install
      bin.install "tidymac"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lu-zhengda/tidymac/releases/download/v0.0.3/tidymac_0.0.3_darwin_arm64.tar.gz"
    sha256 "840f5f14ce97bb5285a6726beca2328ca1ec9a790348690e2a14850aa886e6d7"

    def install
      bin.install "tidymac"
    end
  end

  test do
    system "#{bin}/tidymac", "--version"
  end
end
