# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Whport < Formula
  desc "Port & process manager for macOS"
  homepage "https://github.com/zhengda-lu/whport"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/lu-zhengda/whport/releases/download/v0.1.0/whport_0.1.0_darwin_amd64.tar.gz"
    sha256 "9280948f56a31532d557edea0a5d7e4687dd2428589fd4c9e5a426b0513c9ae1"

    def install
      bin.install "whport"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/lu-zhengda/whport/releases/download/v0.1.0/whport_0.1.0_darwin_arm64.tar.gz"
    sha256 "e69a0543bbf62232872fae7aeada3a3c725059999d57f9b21e67fd22d9d2cf30"

    def install
      bin.install "whport"
    end
  end

  test do
    system "#{bin}/whport", "--version"
  end
end
